---
- hosts: all
  become: true
  tasks:
    - name: Update repository index
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - sngrep
          - sipsak
          - tmux
          - apache2

    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: true
        purge: true

    - name: Run the equivalent of "apt-get clean" as a separate step
      ansible.builtin.apt:
        clean: true
