---
- hosts: all
  become: true

  tasks:
    - name: Play to remove apache
      apt:
        name: apache2
        state: absent

    - name: remove php support for apache
      apt:
        name: libapache2-mod-php
        state: absent
    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: true
        purge: true
